CREATE TABLE users (
   id BIGINT PRIMARY KEY AUTO_INCREMENT,
   name VARCHAR(255) NOT NULL,
   username VARCHAR(255) NOT NULL UNIQUE,
   email VARCHAR(255) NOT NULL UNIQUE,    -- aqui!
   password VARCHAR(255) NOT NULL,
   age INT,
   role VARCHAR(50) NOT NULL
);